### ISSUE TITLE
Not starting after the update

### ISSUE THREAD

**Issue by adamszy** [Sian-Lee-SA/Home-Assistant-Switch-Manager#188]
**I can't launch the extension after the update. Below is the log.**

Logger: homeassistant.setup
Source: setup.py:215
First occurred: 12:42:46 (1 occurrences)
Last logged: 12:42:46

Setup failed for custom integration switch_manager: Unable to import component: cannot import name 'format_schema_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 816, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/switch_manager/__init__.py", line 19, in <module>
    from homeassistant.config import format_schema_error
ImportError: cannot import name 'format_schema_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)

**Comment by Sian-Lee-SA** [comment]
I assume you're not on HA 2023.12+ as stated in the release info?

**Comment by Ra72xx** [comment]
The version requirement is a bit premature, as e.g. HA docker is not even available right now in version 2023.12. So if I don't read the change list carefully, you end up without working switches currently. Fix is easy, fortunately, downgrade for now.

**Comment by adamszy** [comment]
Home Assistant installed on Debian 12 in Docker
Core
2023.11.3
Supervisor
2023.11.6

**Comment by Sian-Lee-SA** [comment]
Ok well for now you will need to stick with the older version till you update HA to 2023.12 (I'm also not aware what version Home Assistant is currently released) The fix was because of issues of others complaining that it wasn't working who are on 2023.12.

**Comment by adamszy** [comment]
I downgraded the version and everything seems to be working
