### ISSUE TITLE
New setup error

### ISSUE THREAD

**Issue by jlabataille** [Sian-Lee-SA/Home-Assistant-Switch-Manager#190]
I upgraded using the latest release (1.3.2-1) but fails setup and will not load, It requires 2023.12.0 (not beta).  So it can only be installed manually, not via HACS. I am using core 2023.12.0b1 with operating System 11.2.rc2,

Error message below.

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 2:57:45 PM (1 occurrences)
Last logged: 2:57:45 PM

Setup failed for custom integration 'switch_manager': Unable to import component: cannot import name '_format_config_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/switch_manager/__init__.py", line 19, in <module>
    from homeassistant.config import _format_config_error
ImportError: cannot import name '_format_config_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)

**Comment by sheepster-9k** [comment]
I'm getting something similar

Logger: homeassistant.config_entries
Source: config_entries.py:2077
First occurred: 10:32:55 AM (1 occurrences)
Last logged: 10:32:55 AM

Error occurred loading flow for integration switch_manager: cannot import name '_format_config_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)


Core
2023.12.0b1
Supervisor
2023.11.6
Operating System
11.2.rc2
Frontend
20231130.0

**Comment by tjorim** [comment]
`_format_config_error` means you have not installed version 1.3.2 or higher.
(1.3.2-1 does not work but you can still download 1.3.2)
