### ISSUE TITLE
_format_config_error in 2023.12 release

### ISSUE THREAD

**Issue by codyc1515** [Sian-Lee-SA/Home-Assistant-Switch-Manager#195]
I am beta testing the 2023.12 HA Core release. This integration is not working with it.

```
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 18:30:11 (1 occurrences)
Last logged: 18:30:11

Setup failed for custom integration 'switch_manager': Unable to import component: cannot import name '_format_config_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/switch_manager/__init__.py", line 19, in <module>
    from homeassistant.config import _format_config_error
ImportError: cannot import name '_format_config_error' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
```

**Comment by Sian-Lee-SA** [comment]
closing as duplicate https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/185
