### ISSUE TITLE
Error doing job: Task exception was never retrieved (None)

### ISSUE THREAD

**Issue by galapiat** [Sian-Lee-SA/Home-Assistant-Switch-Manager#231]
I can't access helpers from HA
I can see the error in HA log

  OS Version:               Home Assistant OS 12.3
  Home Assistant Core:      2024.6.0
  Rabaspberry PI5 

I tried to remove all configuration for the created switch but without any positive effect!
NB: as a new HA user I hope I haven't 

Logger: homeassistant
Source: helpers/config_validation.py:1297
First occurred: 8:36:40 AM (1 occurrences)
Last logged: 8:36:40 AM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/switch_manager/models.py", line 200, in init_script
    self._hass, cv.SCRIPT_SCHEMA(self.sequence)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
        ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 636, in validate_sequence
    cval = validate(index_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 1297, in script_action
    return ACTION_TYPE_SCHEMAS[action](value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
        ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: Service  does not match format <domain>.<name> for dictionary value @ data[0]['service']

**Comment by Sian-Lee-SA** [comment]
could you post a screenshot of your action in yaml mode?

**Comment by galapiat** [comment]
In fact there no action of my side I can see this error after a restart

<img width="690" alt="image" src="https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/132064336/524abda6-5aec-4dfe-9f9e-0fe1c81547a9">

And when I try to open helpers, there is a circle rounding without any answer

And I found somewhere (I can't remember where...) that it's related to Swicth Manager

**Comment by Sian-Lee-SA** [comment]
Hmm strange, Not sure if this is related to the recent changes and Home Assistant deprecating and pinging blocking calls as the cause or not. I also want to be clear, the helpers page on Home Assistant is not related to the helper imports used in switch manager. The error displaying on the trace is generally saying that a sequence yaml from a switch isn't properly constructed and missing fields, but this in no way has any relation to the settings helpers page.

**Comment by galapiat** [comment]
Humm helpers screen appears after I would say 10min!
Then not related to this error you're right
Check yaml doesn't give me any error. I will try to delete all entries in switch manager to see if the error is still here

**Comment by Sian-Lee-SA** [comment]
Glad you got it sorted, as this is the first time this issue has occured and generally reflects a validation for fields by user input being incorrect (kind of like editing your configuration yaml). I'll have a close look if this happens again.
